In [1]:
#1. Import pandas under the alias pd
import pandas as pd

In [3]:
#2. Print the version of pandas that has been imported.
print(pd.__version__)

3.0.0

In [4]:
#3. Print out all the version information of the libraries that are required by the pandas library.
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : 366ccdfcd8ed1e5543bfb6d4ee0c9bc519898670
python                : 3.14.0
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.26200
machine               : AMD64
processor             : Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_India.1252

pandas                : 3.0.0
numpy                 : 2.4.1
dateutil              : 2.9.0.post0
pip                   : 25.3
Cython                : None
sphinx                : None
IPython               : 9.9.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.5
psycopg2              : None
pymysql               : None
pyarrow               : 23.0.0
pyiceberg             : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pytz                  : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
qtpy                  : None
pyqt5                 : None

In [2]:
import numpy as np
# Consider the following Python dictionary data and Python list labels:

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [15]:
#4. Create a DataFrame df from this dictionary data which has the index labels
df=pd.DataFrame(data,index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [16]:
#5. Display a summary of the basic information about this DataFrame and its data (hint: there is a single method that can be called on the DataFrame).
df.info

<bound method DataFrame.info of   animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no>

In [17]:
#6. Return the first 3 rows of the DataFrame df.
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [18]:
#7. Select just the 'animal' and 'age' columns from the DataFrame df.
df[['animal','age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [19]:
#8. Select the data in rows [3, 4, 8] and in columns ['animal', 'age'].
df[["animal",'age']].iloc[[3,4,8]]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [20]:
# 9. Select only the rows where the number of visits is greater than 3.
df[df['visits']>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

In [21]:
# 10. Select the rows where the age is missing, i.e. it is NaN.
df[df.age.isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [22]:
# 11. Select the rows where the animal is a cat and the age is less than 3.
df[(df['animal']=='cat')&(df.age<3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [23]:
# 12. Select the rows the age is between 2 and 4 (inclusive).
df[(df.age<=4) & (df.age>=2)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

In [24]:
# 13. Change the age in row 'f' to 1.5.
df.loc['f','age']=1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [25]:
# 14. Calculate the sum of all visits in df (i.e. find the total number of visits).
df.sum()['visits']

np.int64(19)

In [26]:
#15. Calculate the mean age for each different animal in df.
df.groupby('animal')['age'].agg('mean')

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

In [27]:
df.loc['k']=['cat',3,5,'yes']
df.tail()

  animal  age  visits priority
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    cat  3.0       5      yes

In [28]:
df.drop(index='k',inplace=True)

In [29]:
# 17. Count the number of each type of animal in df.
df['count']=1
df.groupby('animal')['count'].sum()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

In [30]:
# 18. Sort df first by the values in the 'age' in decending order, then by the value in the 'visits' column in ascending order (so row i should be first, and row d should be last).
df.sort_values(by=['age','visits'],ascending=[0,1])

  animal  age  visits priority  count
i    dog  7.0       2       no      1
e    dog  5.0       2       no      1
g  snake  4.5       1       no      1
j    dog  3.0       1       no      1
b    cat  3.0       3      yes      1
a    cat  2.5       1      yes      1
f    cat  1.5       3       no      1
c  snake  0.5       2       no      1
h    cat  NaN       1      yes      1
d    dog  NaN       3      yes      1

In [31]:
# 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be True and 'no' should be False.
df.replace({'no':False,'yes':True})

  animal  age  visits priority  count
a    cat  2.5       1     True      1
b    cat  3.0       3     True      1
c  snake  0.5       2    False      1
d    dog  NaN       3     True      1
e    dog  5.0       2    False      1
f    cat  1.5       3    False      1
g  snake  4.5       1    False      1
h    cat  NaN       1     True      1
i    dog  7.0       2    False      1
j    dog  3.0       1    False      1

In [32]:
# 20. In the 'animal' column, change the 'snake' entries to 'python'.
df.replace({'snake':'Python'})

   animal  age  visits priority  count
a     cat  2.5       1      yes      1
b     cat  3.0       3      yes      1
c  Python  0.5       2       no      1
d     dog  NaN       3      yes      1
e     dog  5.0       2       no      1
f     cat  1.5       3       no      1
g  Python  4.5       1       no      1
h     cat  NaN       1      yes      1
i     dog  7.0       2       no      1
j     dog  3.0       1       no      1

In [33]:
# 21. For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (hint: use a pivot table).
df.pivot_table(values='age',index=['animal'],columns=['visits'], aggfunc='mean')

visits    1    2     3
animal
cat     2.5  NaN  2.25
dog     3.0  6.0   NaN
snake   4.5  0.5   NaN

In [ ]:
# 22. You have a DataFrame df with a column 'A' of integers. For example:

df1 = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
# How do you filter out rows which contain the same integer as the row immediately above?

# You should be left with a column containing the following values:
# 1, 2, 3, 4, 5, 6, 7
df1[df1['A'].ne(df1['A'].shift())]

   A
0  1
1  2
3  3
4  4
5  5
8  6
9  7

In [ ]:
# 23. Given a DataFrame of numeric values, say

df2 = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
# how do you subtract the row mean from each element in the row?
df2=df2-df2.mean(axis=1)
df2

          0         1         2   3   4
0 -0.090929 -0.379361  0.025104 NaN NaN
1  0.154857 -0.038073  0.546433 NaN NaN
2 -0.162971 -0.101690  0.046629 NaN NaN
3  0.023748  0.222212  0.281603 NaN NaN
4  0.338311 -0.383779 -0.132881 NaN NaN

In [ ]:
# 24. Suppose you have DataFrame with 10 columns of real numbers, for example:
# Which column of numbers has the smallest sum? Return that column's label.

df3 = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
display(df3)
df3.sum(axis=0).sort_values().index[0]

,a,b,c,d,e,f,g,h,i,j
0,0.636432,0.358579,0.607853,0.164654,0.981119,0.587959,0.680878,0.017968,0.731755,0.080382
1,0.503549,0.705298,0.546445,0.859233,0.826821,0.543529,0.039925,0.578122,0.734997,0.773906
2,0.599836,0.881438,0.980172,0.227165,0.585364,0.087533,0.952782,0.160169,0.761040,0.363271
3,0.887970,0.933519,0.426527,0.169369,0.107883,0.181626,0.046288,0.254064,0.132657,0.362225
4,0.329332,0.710720,0.912631,0.435140,0.283817,0.507337,0.334661,0.253207,0.739066,0.178565

'h'

In [ ]:
# 25. How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)? As input, use a DataFrame of zeros and ones with 10 rows and 3 columns.

df4 = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
df4
df4.drop_duplicates()

   0  1  2
0  0  1  1
1  0  1  0
2  1  0  1
4  1  1  0
5  1  1  1
7  0  0  1

In [ ]:
# 26. In the cell below, you have a DataFrame df that consists of 10 columns of floating-point numbers. Exactly 5 entries in each row are NaN values.
# For each row of the DataFrame, find the column which contains the third NaN value.
# You should return a Series of column labels: e, c, d, h, d

nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df26 = pd.DataFrame(data, columns=columns)
(df26.isna().cumsum(axis=1)==3).idxmax(axis=1)
#isna to find nan value, cumsum counts the number of nan, idmax returns the column with max value of nan

0    e
1    c
2    d
3    h
4    d
dtype: str

In [ ]:
#27. A DataFrame has a column of groups 'grps' and and column of integer values 'vals':

df27 = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
# For each group, find the sum of the three greatest values. You should end up with the answer as follows:

df27= df27.sort_values(['grps','vals'], ascending=[1,0])
df27['count'] = df27.groupby('grps').cumcount() + 1
#groups by grps and cumcount gives running count for each grp starting from 0(default) +1 to start from 1 as highest 2 as mid and 3 as lowest
df27 = df27.pivot_table(columns='grps', values='vals', index='count')
df27

grps       a     b      c
count
1      345.0  57.0  235.0
2       52.0  54.0   87.0
3       12.0  45.0   23.0
4        4.0   3.0   21.0
5        3.0   1.0   14.0

In [ ]:
df27.cumsum().loc[3]
#loc is used for column additions
#add the number till row 3

grps
a    409.0
b    156.0
c    345.0
Name: 3, dtype: float64

In [ ]:
# # 28. The DataFrame df constructed below has two integer columns 'A' and 'B'. The values in 'A' are between 1 and 100 (inclusive).
# For each group of 10 consecutive integers in 'A' (i.e. (0, 10], (10, 20], ...), calculate the sum of the corresponding values in column 'B'.
# The answer should be a Series as follows:

# A
# (0, 10]      635
# (10, 20]     360
# (20, 30]     315
# (30, 40]     306
# (40, 50]     750
# (50, 60]     284
# (60, 70]     424
# (70, 80]     526
# (80, 90]     835
# (90, 100]    852
df28=pd.DataFrame(np.random.RandomState(8765).randint(1,101,size=(100,2)),columns=['A','B'])
#randomstate is for getting same random integers everytime , randint generates random int from 1-101 with 100 rows and 2 columns
df28.sort_values(['A'])
groups={i/10:f"({i} , {i+10}]"for i in range (0,100,10)}

df28['A']=(df28["A"]-1)//10
df28["A"]=df28["A"].map(groups)
df28.groupby(['A'])['B'].sum()

A
(0 , 10]      635
(10 , 20]     360
(20 , 30]     315
(30 , 40]     306
(40 , 50]     750
(50 , 60]     284
(60 , 70]     424
(70 , 80]     526
(80 , 90]     835
(90 , 100]    852
Name: B, dtype: int32

In [14]:
# 29. Consider a DataFrame df where there is an integer column 'X':

df29 = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
# For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be
# [1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
# Make this a new column 'Y'.


# last_zero=np.where(df29['X']==0,df29.index,-1)
# last_zero=pd.Series(last_zero).replace(-1,np.nan).ffill().fillna(-1)
# df29['Y']=df29.index-last_zero
# df29.loc[df29['X']==0,'Y']=0
# df29

x=(df29['X']!=0).cumsum()
y=x!=x.shift()
df29['Y']=y.groupby((y!=y.shift()).cumsum()).cumsum()
df29

   X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2

In [16]:
# 30. Consider the DataFrame constructed below which contains rows and columns of numerical data.
# Create a list of the column-row index locations of the 3 largest values in this DataFrame. In this case, the answer should be:
# [(5, 7), (6, 4), (2, 5)]

df30=pd.DataFrame(np.random.RandomState(30).randint(1,101,size=(8,8)))
df30.unstack().sort_values()[-3:].index.tolist()
df30

    0   1   2   3   4   5   6   7
0  38  38  46  46  13  24   3  54
1  18  47   4  42   8  66  50  46
2  62  36  19  19  77  17   7  63
3  28  47  46  65  63  12  16  24
4  14  51  34  56  29  59  92  79
5  58  76  96  45  38  76  58  40
6  10  34  48  40  37  23  41  26
7  55  70  91  27  79  92  20  31