In [1]:
import pandas as pd
import numpy as np
coffee = pd.read_csv('./warmup data/coffee.csv')
results = pd.read_parquet('./Data/results.parquet')
bios = pd.read_csv('./Data/bios.csv')
## To read an excel spreadsheet
olympics_data = pd.read_excel('./Data/olympics-data.xlsx', sheet_name="results")
nocs = pd.read_csv('./data/noc_regions.csv')

In [20]:
coffee.loc[[2,3,4], 'Units Sold'] = np.nan
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
2     Tuesday    Espresso         NaN
3     Tuesday       Latte         NaN
4   Wednesday    Espresso         NaN
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [8]:
coffee['Units Sold'].fillna(coffee['Units Sold'].mean())

0     25.000000
1     15.000000
2     34.090909
3     34.090909
4     34.090909
5     25.000000
6     40.000000
7     30.000000
8     45.000000
9     35.000000
10    45.000000
11    35.000000
12    45.000000
13    35.000000
Name: Units Sold, dtype: float64

In [13]:
coffee['Units Sold'].interpolate()

0     25.0
1     15.0
2     17.5
3     20.0
4     22.5
5     25.0
6     40.0
7     30.0
8     45.0
9     35.0
10    45.0
11    35.0
12    45.0
13    35.0
Name: Units Sold, dtype: float64

In [ ]:
coffee.dropna(subset=['Units Sold'])#drops rows containing nan

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [23]:
coffee = pd.read_csv('./warmup data/coffee.csv')
coffee.loc[[2,3,4], 'Units Sold'] = np.nan
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0