In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [30]:
df=np.round(pd.read_csv('Datasets/50_Startups.csv')[['R&D Spend','Administration','Marketing Spend']]/10000)
np.random.seed(9)
df=df.sample(5)
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [31]:
df.iloc[1,0]=np.nan
df.iloc[3,1]=np.nan
df.iloc[-1,-1]=np.nan
df.head()

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [32]:
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())
df0

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [33]:
df1=df0.copy()
df1.iloc[1,0]=np.nan
df1

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [ ]:

    df1=df0.copy()
    df1.iloc[1,0]=np.nan
    X=df1.iloc[[0,2,3,4],1:3]
    y=df1.iloc[[0,2,3,4],0]
    lr=LinearRegression()
    lr.fit(X,y)
    df1.iloc[1,0]=lr.predict(df1.iloc[1,1:].values.reshape(1,2))

    df1.iloc[3,1]=np.nan
    X = df1.iloc[[0,1,2,4],[0,2]]
    y = df1.iloc[[0,1,2,4],1]
    lr=LinearRegression()
    lr.fit(X,y)
    df1.iloc[3,1]=lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))


    df1.iloc[4,-1]=np.nan
    X = df1.iloc[0:4,0:2]
    y=df1.iloc[0:4,-1]
    lr=LinearRegression()
    lr.fit(X,y)
    df1.iloc[4,-1]=lr.predict(df1.iloc[4,0:2].values.reshape(1,2))
    df1

d:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  23.141587        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       11.063618        26.000000
44   2.000000       15.000000        31.601847

In [43]:
df0-df1

    R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37 -13.891587        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000        0.186382         0.000000
44   0.000000        0.000000        -2.351847

In [50]:
df2=df1.copy()
df2.iloc[1,0]=np.nan
X=df2.iloc[[0,2,3,4],1:3]
y=df2.iloc[[0,2,3,4],0]
lr=LinearRegression()
lr.fit(X,y)
df2.iloc[1,0]=lr.predict(df2.iloc[1,1:].values.reshape(1,2))

df2.iloc[3,1]=np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]
lr=LinearRegression()
lr.fit(X,y)
df2.iloc[3,1]=lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))


df2.iloc[4,-1]=np.nan
X = df2.iloc[0:4,0:2]
y=df2.iloc[0:4,-1]
lr=LinearRegression()
lr.fit(X,y)
df2.iloc[4,-1]=lr.predict(df2.iloc[4,0:2].values.reshape(1,2))
df2

d:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  23.828703        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       11.230737        26.000000
44   2.000000       15.000000        39.390436

In [46]:
df1-df2

    R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37  -0.687117        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000       -0.167119         0.000000
44   0.000000        0.000000        -7.788589

Continue till difference become 0 or near