# Loading Data From Files

In [2]:
import pandas as pd
import numpy as np

In [3]:
#to read a csv file
coffee=pd.read_csv("./warmup data/coffee.csv")

In [6]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [7]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [8]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [9]:
coffee.tail(7)

         Day Coffee Type  Units Sold
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [12]:
coffee.sample(10)#random

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
13     Sunday       Latte          35
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
12     Sunday    Espresso          45
9      Friday       Latte          35
11   Saturday       Latte          35
8      Friday    Espresso          45
0      Monday    Espresso          25
5   Wednesday       Latte          25

In [ ]:
coffee.loc[1]#for rows

Day            Monday
Coffee Type     Latte
Units Sold         15
Name: 1, dtype: object

In [ ]:
coffee.iloc[2,0]

'Tuesday'

In [ ]:
coffee.iloc[1:9,1:3]#for rows and column both

  Coffee Type  Units Sold
1       Latte          15
2    Espresso          30
3       Latte          20
4    Espresso          35
5       Latte          25
6    Espresso          40
7       Latte          30
8    Espresso          45

In [33]:
coffee.loc[1:3, "Units Sold"] = 10
display(coffee.head())

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          10
3    Tuesday       Latte          10
4  Wednesday    Espresso          35

In [37]:
coffee["Units Sold"]

0     25
1     10
2     10
3     10
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

In [41]:
coffee.sort_values("Units Sold", ascending=False)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          10
1      Monday       Latte          10
3     Tuesday       Latte          10

In [43]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=[0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          10
1      Monday       Latte          10
3     Tuesday       Latte          10

In [49]:
for index, row in coffee.iterrows():
    print(index)
    print("Coffee Type of Row:", row["Coffee Type"])
    print("\n")

0
Coffee Type of Row: Espresso


1
Coffee Type of Row: Latte


2
Coffee Type of Row: Espresso


3
Coffee Type of Row: Latte


4
Coffee Type of Row: Espresso


5
Coffee Type of Row: Latte


6
Coffee Type of Row: Espresso


7
Coffee Type of Row: Latte


8
Coffee Type of Row: Espresso


9
Coffee Type of Row: Latte


10
Coffee Type of Row: Espresso


11
Coffee Type of Row: Latte


12
Coffee Type of Row: Espresso


13
Coffee Type of Row: Latte